--------------------------------------------------------
--  File created - Wednesday-April-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK_DETAILS
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."BOOK_DETAILS" 
   (	"ISBN_CODE" NUMBER(*,0), 
	"BOOK_TITLE" VARCHAR2(100 BYTE), 
	"LANGUAGE" VARCHAR2(10 BYTE), 
	"BINDING_ID" NUMBER(*,0), 
	"NO_COPIES_ACTUAL" NUMBER(*,0), 
	"NO_COPIES_CURRENT" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER(*,0), 
	"PUBLICATION_YEAR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table BUILDING
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."BUILDING" 
   (	"BUILDINGNAME" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(80 BYTE), 
	"QUALITY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."DEPARTMENT" 
   (	"DEPARTMENTNO" VARCHAR2(8 BYTE), 
	"DEPARTMENTNAME" VARCHAR2(30 BYTE), 
	"MANAGER" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table DOCTOR
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."DOCTOR" 
   (	"GPNAME" VARCHAR2(15 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"SALARY" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table DOSE
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."DOSE" 
   (	"PNO" VARCHAR2(5 BYTE), 
	"DNO" VARCHAR2(5 BYTE), 
	"DOSEDATE" DATE, 
	"QTY" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table Drug
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."Drug" 
   (	"PNO" VARCHAR2(5 BYTE), 
	"PNAME" VARCHAR2(15 BYTE), 
	"TITLE" VARCHAR2(4 BYTE), 
	"DOB" DATE, 
	"CHILDREN" NUMBER(2,0), 
	"GP" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table DRUG
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."DRUG" 
   (	"DNO" VARCHAR2(5 BYTE), 
	"DNAME" VARCHAR2(15 BYTE), 
	"UNIT" VARCHAR2(5 BYTE), 
	"DOI" DATE, 
	"COST" NUMBER(*,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."EMPLOYEE" 
   (	"EMPLOYEENO" VARCHAR2(8 BYTE), 
	"GIVENNAME" VARCHAR2(40 BYTE), 
	"FAMILYNAME" VARCHAR2(40 BYTE), 
	"BIRTHDATE" DATE, 
	"HIREDATE" DATE, 
	"EXTENSIONNO" VARCHAR2(4 BYTE), 
	"SALARY" NUMBER(8,2), 
	"PENSIONCONTRIB" NUMBER(4,2), 
	"JOBTYPE" VARCHAR2(6 BYTE), 
	"MANAGER" VARCHAR2(8 BYTE), 
	"DEPARTMENTNO" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table FLOORSPACE
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."FLOORSPACE" 
   (	"FSID" VARCHAR2(4 BYTE), 
	"FLOORAREA" NUMBER(6,2), 
	"FLOOR" VARCHAR2(2 BYTE), 
	"POSITION" VARCHAR2(20 BYTE), 
	"BUILDINGNAME" VARCHAR2(40 BYTE), 
	"DEPARTMENTNO" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table JOB
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."JOB" 
   (	"JOBTYPE" VARCHAR2(6 BYTE), 
	"JOBDESCRIPTION" VARCHAR2(60 BYTE), 
	"MINSALARY" NUMBER(8,2), 
	"MAXSALARY" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."PATIENT" 
   (	"PNO" VARCHAR2(5 BYTE), 
	"PNAME" VARCHAR2(15 BYTE), 
	"TITLE" VARCHAR2(4 BYTE), 
	"DOB" DATE, 
	"CHILDREN" NUMBER(2,0), 
	"GP" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Table PATIENT2
--------------------------------------------------------

  CREATE TABLE "JI11AAJ"."PATIENT2" 
   (	"COLUMN1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index SYS_C00472490
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."SYS_C00472490" ON "JI11AAJ"."BOOK_DETAILS" ("ISBN_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index BLD_BUILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."BLD_BUILD_PK" ON "JI11AAJ"."BUILDING" ("BUILDINGNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index DPT_DEPNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."DPT_DEPNO_PK" ON "JI11AAJ"."DEPARTMENT" ("DEPARTMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index SYS_C00453581
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."SYS_C00453581" ON "JI11AAJ"."DOCTOR" ("GPNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index EMP_EMPNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."EMP_EMPNO_PK" ON "JI11AAJ"."EMPLOYEE" ("EMPLOYEENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index FLS_ZNEID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."FLS_ZNEID_PK" ON "JI11AAJ"."FLOORSPACE" ("FSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index JOB_JOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."JOB_JOB_PK" ON "JI11AAJ"."JOB" ("JOBTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  DDL for Index PK_PAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "JI11AAJ"."PK_PAT" ON "JI11AAJ"."PATIENT" ("PNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD" ;
--------------------------------------------------------
--  Constraints for Table BOOK_DETAILS
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."BOOK_DETAILS" ADD PRIMARY KEY ("ISBN_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUILDING
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."BUILDING" ADD CONSTRAINT "BLD_BUILD_PK" PRIMARY KEY ("BUILDINGNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."DEPARTMENT" ADD CONSTRAINT "DPT_DEPNO_PK" PRIMARY KEY ("DEPARTMENTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
  ALTER TABLE "JI11AAJ"."DEPARTMENT" MODIFY ("DEPARTMENTNAME" CONSTRAINT "DPT_DNAME_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCTOR
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."DOCTOR" ADD PRIMARY KEY ("GPNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "PGRAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOSE
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."DOSE" MODIFY ("PNO" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."DOSE" MODIFY ("DNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table Drug
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("PNO" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("PNAME" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("CHILDREN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."Drug" MODIFY ("GP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_EMPNO_PK" PRIMARY KEY ("EMPLOYEENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
  ALTER TABLE "JI11AAJ"."EMPLOYEE" MODIFY ("FAMILYNAME" CONSTRAINT "EMP_FNAME_NN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."EMPLOYEE" MODIFY ("GIVENNAME" CONSTRAINT "EMP_GNAME_NN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."EMPLOYEE" MODIFY ("HIREDATE" CONSTRAINT "EMP_HDATE_NN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_PENCO_CK" CHECK (PensionContrib >= 0) ENABLE;
  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_SALRY_CK" CHECK (Salary >= 0) ENABLE;
  ALTER TABLE "JI11AAJ"."EMPLOYEE" MODIFY ("SALARY" CONSTRAINT "EMP_SALRY_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FLOORSPACE
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."FLOORSPACE" MODIFY ("BUILDINGNAME" CONSTRAINT "FLS_BUILD_NN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."FLOORSPACE" MODIFY ("FLOORAREA" CONSTRAINT "FLS_FAREA_NN" NOT NULL ENABLE);
  ALTER TABLE "JI11AAJ"."FLOORSPACE" ADD CONSTRAINT "FLS_ZNEID_PK" PRIMARY KEY ("FSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOB
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."JOB" ADD CONSTRAINT "JOB_JOB_PK" PRIMARY KEY ("JOBTYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
  ALTER TABLE "JI11AAJ"."JOB" ADD CONSTRAINT "JOB_MAXSY_CK" CHECK (MaxSalary > MinSalary) ENABLE;
  ALTER TABLE "JI11AAJ"."JOB" ADD CONSTRAINT "JOB_MINSY_CK" CHECK (MinSalary >= 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."PATIENT" ADD CONSTRAINT "PK_PAT" PRIMARY KEY ("PNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PGRAD"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."DEPARTMENT" ADD CONSTRAINT "DPT_MNGER_FK" FOREIGN KEY ("MANAGER")
	  REFERENCES "JI11AAJ"."EMPLOYEE" ("EMPLOYEENO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_DEPNO_FK" FOREIGN KEY ("DEPARTMENTNO")
	  REFERENCES "JI11AAJ"."DEPARTMENT" ("DEPARTMENTNO") ENABLE;
  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_JOBTY_FK" FOREIGN KEY ("JOBTYPE")
	  REFERENCES "JI11AAJ"."JOB" ("JOBTYPE") ENABLE;
  ALTER TABLE "JI11AAJ"."EMPLOYEE" ADD CONSTRAINT "EMP_MNGER_FK" FOREIGN KEY ("MANAGER")
	  REFERENCES "JI11AAJ"."EMPLOYEE" ("EMPLOYEENO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLOORSPACE
--------------------------------------------------------

  ALTER TABLE "JI11AAJ"."FLOORSPACE" ADD CONSTRAINT "FLS_BLDNO_FK" FOREIGN KEY ("BUILDINGNAME")
	  REFERENCES "JI11AAJ"."BUILDING" ("BUILDINGNAME") ENABLE;
  ALTER TABLE "JI11AAJ"."FLOORSPACE" ADD CONSTRAINT "FLS_DEPNO_FK" FOREIGN KEY ("DEPARTMENTNO")
	  REFERENCES "JI11AAJ"."DEPARTMENT" ("DEPARTMENTNO") ENABLE;
